### ISSUE TITLE
Review os-main code & docs, then merge to main

### ISSUE THREAD

**Issue by joewxboy** [open-horizon-services/service-edgelake#2]
@t-fine Please review.  Reach out to @joewxboy and @oshadmon with any questions.

**Comment by oshadmon** [comment]
@t-fine , I reviewed to make sure configurations look right and added a document about kubearmor, its up to you what to keep / reorg / edit as you see fit. 

Thanks!

**Comment by t-fine** [comment]
@joewxboy @oshadmon so just a first pass review, the `Open Horizon.md` file definitely will need to be updated since it's mostly based on IBM Edge Application Manager and points to that documentation as opposed to the open source docs and process. I'm okay with merging this as is so more progress can be made, and opening issues to address these things in the near future. What does everybody think?

**Comment by oshadmon** [comment]
@t-fine 
1. I updated the name of the file form `Open Horizon` to `Edge Service` -- I'd appreciate keeping it for now
2. I don't remember how to do the patterns (ie the "newer" / "better" way), if you can shoot me quick directions I can try to create a document for that. 

What else are we missing if we want to merge this **before** the next Open Horizon call? 

Thanks 
- Ori

**Comment by t-fine** [comment]
Okay no worries, I've gone ahead and merged it as-is. Joe mentioned creating some Open Horizon artifacts with the help of Sanjeev next so we can work on getting those added and maybe some accompanying documentation tweaks to create a deployment policy and perhaps pattern as well!

**Comment by t-fine** [comment]
Merged code into main. We can open issues to polish the repo separately. Closing.
